.gitignore
DAIRemote/displayConfig.json

Updated .gitignore for Android Studio and removed a generated save file for display settings.

Updated .gitignore for Android Studio

---

DAIRemoteApp/app/src/main/AndroidManifest.xml
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/RemotePage.java
DAIRemoteApp/app/src/main/res/layout/activity_remote_page.xml

* Added functionality to scan for nearby devices by IP address
* Displayed the list of discovered devices, including their names and addresses
* Handled cases where the device name is null by displaying a placeholder name "Unknown Device"

Implemented local IP address detection for nearby devices

---

DAIRemote/Form1.cs
DAIRemote/UDPServer.cs
DAIRemoteApp/app/src/main/AndroidManifest.xml
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/InteractionPage.java
DAIRemoteApp/app/src/main/res/drawable/interactions_help_icon.xml
DAIRemoteApp/app/src/main/res/drawable/udpmsg_icon.xml
DAIRemoteApp/app/src/main/res/layout/activity_interaction_page.xml

* Implemented UDP server for host and client communication. 
* Updated app interactions page to send host interaction information. 
* Implemented initialization of server on launch of desktop application.

Implemented UDP server for host and client communication

---

DisplayProfileManager/DisplayConfig.cs

Fixed and implemented functions to load and apply display settings taken from a JSON file.

Implemented functions to load and apply display configurations.

---

DAIRemote/Form1.cs
DAIRemote/Form1.designer.cs
DisplayProfileManager/DisplayConfig.cs

* Centered window on launch and added text box for display profile name
* Modified SaveDisplaySettings to output to a subfolder in %appdata%. Added check to ensure folder exists, otherwise create one.

Modified SaveDisplaySettings Output Location & Added Textbox for Profile Name

---

DAIRemote/DAIRemoteApplicationUI.cs
DAIRemote/SystemTray.cs
DAIRemoteApp/app/src/main/AndroidManifest.xml
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/ConnectionManager.java
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/InteractionPage.java
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/MainActivity.java
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/ServersPage.java
DAIRemoteApp/app/src/main/res/drawable/keyboard_toolbar_arrowdown.xml
DAIRemoteApp/app/src/main/res/drawable/keyboard_toolbar_arrowleft.xml
DAIRemoteApp/app/src/main/res/drawable/keyboard_toolbar_arrowright.xml
DAIRemoteApp/app/src/main/res/drawable/keyboard_toolbar_arrowup.xml
DAIRemoteApp/app/src/main/res/layout/activity_interaction_page.xml
DAIRemoteApp/app/src/main/res/layout/activity_main.xml
DAIRemoteApp/app/src/main/res/layout/activity_servers_page.xml
DAIRemoteApp/app/src/main/res/values/styles.xml
DisplayProfileManager/DisplayConfig.cs
DisplayProfileManager/DisplayProfileManager.csproj
UDPServerManager/MouseOperations.cs
UDPServerManager/UDPServerManager.cs

* Implemented toggling for CTRL, SHIFT, and ALT and handling for sending key combinations with special keys.
* Utilized code cleanup and import optimization provided by android studio.
* Tried something different with host discovery.
* Replaced notification system with toasts. 
* Improved on back press functionality and made some optimizations for the app.
* Added grid layout to interaction page shortcuts.
* Enlarged arrow icons in keyboard toolbar.
* Implemented proper tracking of keyboard visibility and cleaned up functions related to that accordingly. 
* Added better implementation of displaying user keyboard input without hindering mouse movement.

Redesigned App Notification System & Further Improved App Keyboard Implementation

---

AudioManager/AudioDeviceManager.cs
AudioManager/AudioManager.csproj
AudioManager/AudioOutputForm.cs
AudioManager/Program.cs
DAIRemote/DAIRemoteApplicationUI.cs
DAIRemote/DAIRemoteApplicationUI.designer.cs

* Implemented setting audio device 
* Implemented audio device cycling 
* Implemented modifying volume
* Added functionality to audio drop down menu for demo

Transitioned Nuget Packages from NAudio to AudioSwitcher.AudioAPI.CoreAudio

---

DAIRemoteApp/app/src/main/java/com/example/dairemote_app/ConnectionManager.java
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/InteractionPage.java
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/InteractiveTutorial.java
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/MainActivity.java
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/ServersPage.java
DAIRemoteApp/app/src/main/res/drawable/baseline_add_24.xml
DAIRemoteApp/app/src/main/res/layout/activity_servers_page.xml
DAIRemoteApp/app/src/main/res/layout/list_item.xml

- Included handling of invalid host entered with pop-up letting user know after certain amount of time attempting connection
- Included case where on MainActivity page if no hosts are found, then automatically switches to ServerPage to allow user to manually add their server host
- Changed font color & font of listview of hosts for presentability
- Added additional step in tutorial for ServersPage
- Fixed bug where when tutorial is on from Main page and there's a failed host connection then switching to the ServersPage, tutorial would give instructions in reference to RemotePage--now it shows correct steps corresponding to ServersPage

Implemented 'add server host' button for user input of server host

---

AudioManager/AudioDeviceManager.cs
AudioManager/AudioOutputForm.cs
DAIRemote/DAIRemoteApplicationUI.cs
DAIRemote/DAIRemoteApplicationUI.designer.cs
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/InteractionPage.java

* Implemented listening to audio playback device state changes. Dropdown menu now updates with state changes.
* Updated application black text to white. Applied this to display load/delete buttons as well.
* Fixed bug with app sending 2 finger tap action following every 3 finger tap action.

Implemented eventhandlers for AudioDeviceManager and AudioOutputForm & Updated text colors

---

AudioManager/AudioDeviceManager.cs
AudioManager/AudioOutputForm.cs
AudioManager/Program.cs
DAIRemote/.editorconfig
DAIRemote/DAIRemote.sln
DAIRemote/DAIRemoteApplicationUI.cs
DAIRemote/DAIRemoteApplicationUI.designer.cs
DAIRemote/SystemTray.cs
DisplayProfileManager/DisplayConfig.cs
UDPServerManager/DeviceHistoryManager.cs
UDPServerManager/MouseManager.cs
UDPServerManager/UDPServerManager.cs
UDPServerManager/WindowsKey.cs

* Renamed various methods with VS projects.
* Added .editorconfig and applied most suggestions to standardize code among multiple collaborators.

Application of .editorconfig to standardize and cleanup VS project

---

DAIRemoteApp/app/src/main/java/com/example/dairemote_app/ConnectionMonitor.java
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/InteractionPage.java

* Improved handling of disconnects from the host on the client.
* Differentiated connection lost vs intentional disconnects by the client in notifications.

Improved handling of disconnects from the host on the client

---

DAIRemote/DAIRemoteApplicationUI.cs
DAIRemote/DAIRemoteApplicationUI.designer.cs
DAIRemote/HotkeyManager.cs
DAIRemote/SystemTray.cs
DisplayProfileManager/DisplayConfig.cs
UDPServerManager/UDPServerManager.cs

* Ensured all references to display profile directory and files are called through the DisplayConfig class.

Display Profile Directory and Files Called through DisplayConfig

---

DAIRemote/DAIRemoteApplicationUI.cs
DAIRemote/DAIRemoteApplicationUI.designer.cs

-Changed some form element names such as button1 and button2 to more meaningful names.
-Fixed overlap in some form elements.
-Tweaked position of some form elements to make the UI look more visually appealing and less cramped.
-Moved audio dropdown menu to bottom of UI.
-Changed color of load and delete profile text above flow layout panels.

Improved the combined desktop UI.

---

DAIRemoteApp/app/build.gradle.kts
DAIRemoteApp/app/src/test/java/android/util/Log.java
DAIRemoteApp/app/src/test/java/com/example/dairemote_app/ConnectionManagerTest.java
DAIRemoteApp/app/src/test/java/com/example/dairemote_app/KeyboardToolbarTest.java
DAIRemoteApp/gradle/libs.versions.toml

JUnit 5 Unit Testing for ConnectionManager.Java and KeyboardToolbar.Java

JUnit 5 Unit Testing for ConnectionManager.Java and KeyboardToolbar.Java

---

.github/workflows/gradle.yml

Updated gradle.yml to include JUnit 5 Unit Testing

Updated gradle.yml to include JUnit 5 Unit Testing

---

DAIRemote.tests/DAIRemote.tests.csproj
DAIRemote.tests/SystemTrayTest.cs
DAIRemote/DAIRemote.csproj

added unit tests for system tray

Shawinder minhas unittest

---

DAIRemoteApp/app/src/main/java/com/example/dairemote_app/SocketManager.java
DAIRemoteApp/app/src/test/java/com/example/dairemote_app/SocketManagerTest.java

Unit test for Socket Manager class
Methods:
SetSocket()
GetSocket()
CloseSocket()
GetData()
SetPacket()
GetPacket()

Lynn Hakim Unit test

---

INSTALLATION.md
README.md

- Added INSTALLATION.md and updated info both on there and README.md

Added INSTALLATION.md

---

AudioManager/AudioManager.csproj
AudioManager/Program.cs
DAIRemote.tests/DAIRemote.tests.csproj
DAIRemote/DAIRemote.csproj
DAIRemote/DAIRemote.sln
DisplayProfileManager/DisplayProfileManager.csproj
UDPServerManager/Program.cs
UDPServerManager/UDPServerManager.csproj

* Modified Project Properties to Publish Single EXE.

Modified Project Properties to Publish Single EXE

---

DAIRemote.tests/SystemTrayTest.cs
DAIRemote/SystemTray.cs
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/fragments/InteractionFragment.kt
DAIRemoteApp/gradle.properties
DisplayProfileManager/DisplayConfig.cs
UDPServerManager/ConnectionPromptForm.cs
UDPServerManager/UDPServerManager.cs
UDPServerManager/WindowServiceAdvertiser.cs

* Ensured stopping and restarting of mdns advertising according to user connection state.
* Ensured edit text is cleared upon pressing enter on the app.
* Lowered heartbeat timeout.
* Applied visual studio cleaning profile

DAIRemote Cleanup (#6)

---

DAIRemote.tests/SystemTrayTest.cs
DAIRemote/SystemTray.cs
DAIRemoteApp/app/src/main/java/com/example/dairemote_app/fragments/InteractionFragment.kt
DAIRemoteApp/gradle.properties
DisplayProfileManager/DisplayConfig.cs
UDPServerManager/ConnectionPromptForm.cs
UDPServerManager/UDPServerManager.cs
UDPServerManager/WindowServiceAdvertiser.cs

* Ensured stopping and restarting of mdns advertising according to user connection state.
* Ensured edit text is cleared upon pressing enter on the app.
* Lowered heartbeat timeout.
* Applied visual studio cleaning profile

DAIRemote Cleanup (#6) (#134)
